// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RikardQLAssignment.api.DataAccess;

namespace RikardQLAssignment.api.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RikardQLAssignment.api.Models.Position", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Latitude = "41.7325",
                            Longitude = "49.9469",
                            Title = "Middle of the Caspian sea"
                        },
                        new
                        {
                            Id = "1",
                            Latitude = "36.4511",
                            Longitude = "28.2278",
                            Title = "Colossus of Rhodes"
                        },
                        new
                        {
                            Id = "2",
                            Latitude = "44.244167",
                            Longitude = "7.769444",
                            Title = "Pink Rabbit was once here"
                        },
                        new
                        {
                            Id = "3",
                            Latitude = "59.3293",
                            Longitude = "18.0686",
                            Title = "Stockholm, capital of Sweden"
                        },
                        new
                        {
                            Id = "4",
                            Latitude = "59.9139",
                            Longitude = "10.7522",
                            Title = "Oslo, capital of Norway"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
